# Generated by Django 4.0.5 on 2022-06-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='xingming')),
                ('sex', models.BooleanField(default=1, verbose_name='sex')),
                ('age', models.IntegerField(verbose_name='age')),
                ('class_num', models.CharField(max_length=5, verbose_name='class num')),
                ('description', models.TextField(max_length=1000, verbose_name='person description')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'student',
                'db_table': 'tb_student',
            },
        ),
    ]
